export interface CardItem {
  id: number;
  numStr: string;
  chapterId: number;
  chapterTitle: string;
  tier: string;
  tierNum: number;
  name: string;
  photoTitle: string;
  voiceover: string;
  backupTitle: string;
}

export interface ChapterInfo {
  id: number;
  title: string;
  shortTitle: string;
  cardsRange: string;
  cardCount: number;
  tierName: string;
  tierNum: number;
  accentColor: string;
  bgGradient: string;
  borderAccent: string;
  badgeBg: string;
  badgeText: string;
  description: string;
}

export const CHAPTERS: ChapterInfo[] = [
  {
    id: 0,
    title: 'Пролог — МАТЧ БЕЗ ТЕБЕ',
    shortTitle: 'Пролог',
    cardsRange: '01',
    cardCount: 1,
    tierName: 'Рівень 0 · Точка входу',
    tierNum: 0,
    accentColor: '#f59e0b', // Amber
    bgGradient: 'from-amber-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-amber-500/40',
    badgeBg: 'bg-amber-500/20',
    badgeText: 'text-amber-300',
    description: 'Вступний епізод: помилка появи, початок розслідування та падіння замість спавну.',
  },
  {
    id: 1,
    title: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    shortTitle: 'Глава 1',
    cardsRange: '02–09',
    cardCount: 8,
    tierName: 'Рівень 1 · Поверхня',
    tierNum: 1,
    accentColor: '#10b981', // Emerald
    bgGradient: 'from-emerald-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-emerald-500/40',
    badgeBg: 'bg-emerald-500/20',
    badgeText: 'text-emerald-300',
    description: 'Ранні баги, легендарний Bite the Dust, кущі, неіснуючі двері та нерухома курка.',
  },
  {
    id: 2,
    title: '2. ВИХОДИМО З ГРИ',
    shortTitle: 'Глава 2',
    cardsRange: '10–17',
    cardCount: 8,
    tierName: 'Рівень 2 · Фольклор',
    tierNum: 2,
    accentColor: '#06b6d4', // Cyan
    bgGradient: 'from-cyan-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-cyan-500/40',
    badgeBg: 'bg-cyan-500/20',
    badgeText: 'text-cyan-300',
    description: 'Шкільні листівки, міфічний гравець Дем’ян, карпатська ложка, меми та першородний унітаз.',
  },
  {
    id: 3,
    title: '3. УСЕ ПІД КОНТРОЛЕМ',
    shortTitle: 'Глава 3',
    cardsRange: '18–31',
    cardCount: 14,
    tierName: 'Рівень 3 · Золота доба',
    tierNum: 3,
    accentColor: '#8b5cf6', // Violet
    bgGradient: 'from-violet-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-violet-500/40',
    badgeBg: 'bg-violet-500/20',
    badgeText: 'text-violet-300',
    description: 'Версія 1.7.32: Loadout, стрільба в меню, бананові снайперки, батлпас, кейси та рулетка.',
  },
  {
    id: 4,
    title: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    shortTitle: 'Глава 4',
    cardsRange: '32–42',
    cardCount: 11,
    tierName: 'Рівень 4 · Аномалії та PvP',
    tierNum: 4,
    accentColor: '#f97316', // Orange
    bgGradient: 'from-orange-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-orange-500/40',
    badgeBg: 'bg-orange-500/20',
    badgeText: 'text-orange-300',
    description: 'Бій із Сізіфом, безсмертя в кутах, безкінечні матчі на 4 команди, Towers та гальмуючий 7-Eleven.',
  },
  {
    id: 5,
    title: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    shortTitle: 'Глава 5',
    cardsRange: '43–53',
    cardCount: 11,
    tierName: 'Рівень 5 · Епоха Некстботів',
    tierNum: 5,
    accentColor: '#ef4444', // Red
    bgGradient: 'from-red-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-red-500/40',
    badgeBg: 'bg-red-500/20',
    badgeText: 'text-red-300',
    description: 'Зміна жанру: двері 4445, продавець Скібіді, таємна кімната з котом, хінкалі та невідворотний Соул Гудман.',
  },
  {
    id: 6,
    title: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    shortTitle: 'Глава 6',
    cardsRange: '54–58',
    cardCount: 5,
    tierName: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    accentColor: '#14b8a6', // Teal
    bgGradient: 'from-teal-950/30 via-slate-900/60 to-slate-950/80',
    borderAccent: 'border-teal-500/40',
    badgeBg: 'bg-teal-500/20',
    badgeText: 'text-teal-300',
    description: 'Найглибший шар: версія 146, рушій ACS, жовтий лабіринт, двері в порожнечу і перша коробка (34).',
  },
];

export const CARDS_DATA: CardItem[] = [
  /* Пролог (01) */
  {
    id: 1,
    numStr: '01',
    chapterId: 0,
    chapterTitle: 'Пролог — МАТЧ БЕЗ ТЕБЕ',
    tier: 'Рівень 0 · Початок',
    tierNum: 0,
    name: 'Падіння зі спавну',
    photoTitle: 'МАТЧ БЕЗ ТЕБЕ',
    voiceover: 'Матч без тебе.',
    backupTitle: 'ПАДІННЯ ЗАМІСТЬ ПОЯВИ',
  },

  /* Глава 1 (02–09) */
  {
    id: 2,
    numStr: '02',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Backrooms FPS (1148)',
    photoTitle: 'ГРА, ПРО ЯКУ ВИ МОГЛИ НЕ ЧУТИ',
    voiceover: 'Гра, про яку ви могли не чути.',
    backupTitle: 'BACKROOMS FPS: ВЕРСІЯ 1148',
  },
  {
    id: 3,
    numStr: '03',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Bite the dust',
    photoTitle: 'ДОМІВКА МІСЦЕВИХ ЛЕГЕНД',
    voiceover: 'Домівка місцевих легенд.',
    backupTitle: 'DUST 2, АЛЕ НАША',
  },
  {
    id: 4,
    numStr: '04',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Старий Bite the dust',
    photoTitle: 'BITE THE DUST БЕЗ ЗАЙВОГО',
    voiceover: 'Байт зе даст без зайвого.',
    backupTitle: 'МАПА ДО ПРИКРАС',
  },
  {
    id: 5,
    numStr: '05',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Маскування за кущем',
    photoTitle: 'СТАНЬ КУЩЕМ',
    voiceover: 'Стань кущем.',
    backupTitle: 'РОСЛИННА ТАКТИКА',
  },
  {
    id: 6,
    numStr: '06',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Паркур та підсади',
    photoTitle: 'ТРОЄ — НА ПАЛЬМУ',
    voiceover: 'Троє — на пальму.',
    backupTitle: 'ЗА МЕЖІ МАПИ',
  },
  {
    id: 7,
    numStr: '07',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Двері без колізії',
    photoTitle: 'ДВЕРІ, ЯКІ НЕ ІСНУЮТЬ',
    voiceover: 'Двері, які не існують.',
    backupTitle: 'ПРОЙТИ КРІЗЬ ДВЕРІ',
  },
  {
    id: 8,
    numStr: '08',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Вбивство спектаторів',
    photoTitle: 'СПОСТЕРІГАЧА ТЕЖ МОЖНА ВБИТИ',
    voiceover: 'Спостерігача теж можна вбити.',
    backupTitle: 'НЕБЕЗПЕЧНИЙ ПЕРЕГЛЯД',
  },
  {
    id: 9,
    numStr: '09',
    chapterId: 1,
    chapterTitle: '1. БУДЬ ЛАСКА, ГРАЙТЕ ПРАВИЛЬНО',
    tier: 'Рівень 1 · Поверхня',
    tierNum: 1,
    name: 'Курка',
    photoTitle: 'ВОНА ПРОСТО ДИВИТЬСЯ',
    voiceover: 'Вона просто дивиться.',
    backupTitle: 'НЕРУХОМИЙ СВІДОК',
  },

  /* Глава 2 (10–17) */
  {
    id: 10,
    numStr: '10',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Листівки',
    photoTitle: 'РЕКЛАМА ЗІ ШКІЛЬНОГО ПРИНТЕРА',
    voiceover: 'Реклама зі шкільного принтера.',
    backupTitle: 'ЛИСТІВКА ДЛЯ СВОЇХ',
  },
  {
    id: 11,
    numStr: '11',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Дем’ян',
    photoTitle: 'СУПЕРНИК САМОГО ТВОРЦЯ',
    voiceover: 'Суперник самого творця.',
    backupTitle: 'ГРАВЕЦЬ, ЯКОГО ЗАПАМ’ЯТАЛИ',
  },
  {
    id: 12,
    numStr: '12',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Flashbomb',
    photoTitle: 'НАЗВА, ЯКА ПРИЖИЛАСЯ',
    voiceover: 'Назва, яка прижилася.',
    backupTitle: 'ОДИН ГРАВЕЦЬ — СПІЛЬНИЙ СЛОВНИК',
  },
  {
    id: 13,
    numStr: '13',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Wood spoon',
    photoTitle: 'ЛОЖКА З КАРПАТ',
    voiceover: 'Ложка з карпат.',
    backupTitle: 'СУВЕНІР, ЯКИЙ СТАВ ЗБРОЄЮ',
  },
  {
    id: 14,
    numStr: '14',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Піраміда та Курятник',
    photoTitle: 'З УРОКУ — НА МАПУ',
    voiceover: 'З уроку — на мапу.',
    backupTitle: 'ВІД КУРЯТНИКА ДО ПІРАМІДИ',
  },
  {
    id: 15,
    numStr: '15',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Фото на стінах',
    photoTitle: 'МУЗЕЙ МЕМІВ',
    voiceover: 'Музей мемів.',
    backupTitle: 'СТІНИ З ПАМ’ЯТТЮ',
  },
  {
    id: 16,
    numStr: '16',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Toilet Fighters',
    photoTitle: 'МАПА, ЯКОЇ БРАКУЄ',
    voiceover: 'Мапа, якої бракує.',
    backupTitle: 'ТУНЕЛЬ ДО СПОГАДІВ',
  },
  {
    id: 17,
    numStr: '17',
    chapterId: 2,
    chapterTitle: '2. ВИХОДИМО З ГРИ',
    tier: 'Рівень 2 · Фольклор',
    tierNum: 2,
    name: 'Toilet',
    photoTitle: 'ПЕРШОРОДНИЙ УНІТАЗ',
    voiceover: 'Першородний унітаз.',
    backupTitle: 'ПРАЩУР КУРКИ?',
  },

  /* Глава 3 (18–31) */
  {
    id: 18,
    numStr: '18',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Backrooms FPS 1.7.32 (926)',
    photoTitle: 'ТА САМА ЗОЛОТА ДОБА',
    voiceover: 'Та сама золота доба.',
    backupTitle: 'ОНОВЛЕННЯ 1.7.32',
  },
  {
    id: 19,
    numStr: '19',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Loadout',
    photoTitle: 'АРСЕНАЛ ПЕРЕД БОЄМ',
    voiceover: 'Арсенал перед боєм.',
    backupTitle: 'ОБЕРИ, З ЧИМ ПІДЕШ',
  },
  {
    id: 20,
    numStr: '20',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Головне меню',
    photoTitle: 'КРАСИВО. АЛЕ ЧИ ПРАЦЮЄ?',
    voiceover: 'Красиво. Але чи працює?',
    backupTitle: 'НАЛАШТУВАННЯ З ПІДСТУПОМ',
  },
  {
    id: 21,
    numStr: '21',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Тир у меню',
    photoTitle: 'ЧЕКАННЯ ЯК МІНІГРА',
    voiceover: 'Чекання як мінігра.',
    backupTitle: 'ПОТРЕНУЙСЯ, ПОКИ ЧЕКАЄШ',
  },
  {
    id: 22,
    numStr: '22',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Зброя в меню',
    photoTitle: 'МЕНЮ ПІД ПРИЦІЛОМ',
    voiceover: 'Меню під прицілом.',
    backupTitle: 'ЗІ ЗБРОЄЮ ДО ПОЧАТКУ МАТЧУ',
  },
  {
    id: 23,
    numStr: '23',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Alpha Engine',
    photoTitle: 'КУЛІ ЛЕТІЛИ, КУДИ ХОТІЛИ',
    voiceover: 'Кулі летіли, куди хотіли.',
    backupTitle: 'СТРІЛЬБА З ХАРАКТЕРОМ',
  },
  {
    id: 24,
    numStr: '24',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Банани та Картопля',
    photoTitle: 'ДОВГИЙ БАНАН — СНАЙПЕРКА',
    voiceover: 'Довгий банан — снайперка.',
    backupTitle: 'ЇСТІВНИЙ АРСЕНАЛ',
  },
  {
    id: 25,
    numStr: '25',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Mushroom',
    photoTitle: 'ГРИБ, ЯКИЙ ВИБУХАЄ',
    voiceover: 'Гриб, який вибухає.',
    backupTitle: 'ГРАНАТА В МИЛІЙ ОБГОРТЦІ',
  },
  {
    id: 26,
    numStr: '26',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Spectator mode',
    photoTitle: 'РЕЖИМ, ЯКИЙ ПРИБРАЛИ',
    voiceover: 'Режим, який прибрали.',
    backupTitle: 'СПОСТЕРІГАЧ З ПРОБЛЕМАМИ',
  },
  {
    id: 27,
    numStr: '27',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Battlepass',
    photoTitle: 'ТРИ ЗАВДАННЯ НА ДЕНЬ',
    voiceover: 'Три завдання на день.',
    backupTitle: 'ЗАЙДИ ЩЕ РАЗ',
  },
  {
    id: 28,
    numStr: '28',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Кейси та Ножі',
    photoTitle: 'КРАСИВО ≠ КОРИСНО',
    voiceover: 'Красиво — не означає корисно.',
    backupTitle: 'НОЖІ СЕРЕД ПЕРЕСТРІЛОК',
  },
  {
    id: 29,
    numStr: '29',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Колесо фортуни',
    photoTitle: 'ЩОДЕННА СПРОБА УДАЧІ',
    voiceover: 'Щоденна спроба удачі.',
    backupTitle: 'КРУТИ Й ДИВИСЯ',
  },
  {
    id: 30,
    numStr: '30',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'M249 та Катана',
    photoTitle: 'ПЛАТНИЙ АРСЕНАЛ',
    voiceover: 'Платний арсенал.',
    backupTitle: 'КУЛЕМЕТ І ЗАБУТА КАТАНА',
  },
  {
    id: 31,
    numStr: '31',
    chapterId: 3,
    chapterTitle: '3. УСЕ ПІД КОНТРОЛЕМ',
    tier: 'Рівень 3 · Золота доба',
    tierNum: 3,
    name: 'Подарунок',
    photoTitle: 'ПОДАРУНОК БЕЗ НАГОРОДИ',
    voiceover: 'Подарунок без нагороди.',
    backupTitle: 'КОРОБКА ОЧІКУВАНЬ',
  },

  /* Глава 4 (32–42) */
  {
    id: 32,
    numStr: '32',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Sisyphus fight',
    photoTitle: 'СПАВН ПІД ОБСТРІЛОМ',
    voiceover: 'Спавн під обстрілом.',
    backupTitle: 'СІЗІФ ПОВЕРТАЄТЬСЯ В БІЙ',
  },
  {
    id: 33,
    numStr: '33',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Salvage',
    photoTitle: 'ЗИМА. ОФІС. М’ЯСОРУБКА.',
    voiceover: 'Зима. Офіс. М’ясорубка.',
    backupTitle: 'ЗНОВУ ТІ САМІ ГРАБЛІ',
  },
  {
    id: 34,
    numStr: '34',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Невразливість у кутах',
    photoTitle: 'КУТОК БЕЗСМЕРТТЯ',
    voiceover: 'Куток безсмерття.',
    backupTitle: 'ГЕОМЕТРІЯ ПРОТИ КУЛЬ',
  },
  {
    id: 35,
    numStr: '35',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Backrooms FPS (276)',
    photoTitle: 'МАТЧ БЕЗ ТАЙМЕРА',
    voiceover: 'Матч без таймера.',
    backupTitle: 'ВІЙНА НА ВИСНАЖЕННЯ',
  },
  {
    id: 36,
    numStr: '36',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: '4 команди',
    photoTitle: 'ВІЙНА НА ЧОТИРИ ФРОНТИ',
    voiceover: 'Війна на чотири фронти.',
    backupTitle: 'ЧОТИРИ КОЛЬОРИ БОЮ',
  },
  {
    id: 37,
    numStr: '37',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Symetric backrooms map',
    photoTitle: 'МАПА-ДЗЕРКАЛО',
    voiceover: 'Мапа-дзеркало.',
    backupTitle: 'СИМЕТРІЯ СЕРЕД ХАОСУ',
  },
  {
    id: 38,
    numStr: '38',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Безпечні зони',
    photoTitle: 'МЕЖА БЕЗПЕЧНОЇ ЗОНИ',
    voiceover: 'Межа безпечної зони.',
    backupTitle: 'СЮДИ ВОРОГ НЕ ПРОЙДЕ',
  },
  {
    id: 39,
    numStr: '39',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Towers',
    photoTitle: 'НЕДОБУДОВАНИЙ РАЙ',
    voiceover: 'Недобудований рай.',
    backupTitle: 'ВЕЖІ, ЯКІ НЕ ДОРОБИЛИ',
  },
  {
    id: 40,
    numStr: '40',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Pvp zone',
    photoTitle: 'З’ЯСУЄМО, ХТО З НАС ПРО',
    voiceover: 'З’ясуємо, хто з нас про.',
    backupTitle: 'ДУЕЛЬ 1 НА 1',
  },
  {
    id: 41,
    numStr: '41',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: '7 eleven',
    photoTitle: '7-ELEVEN: ЛАГИ В КОМПЛЕКТІ',
    voiceover: 'Севен-ілевен. Лаги в комплекті.',
    backupTitle: 'МАПА, ЯКА ГАЛЬМУВАЛА',
  },
  {
    id: 42,
    numStr: '42',
    chapterId: 4,
    chapterTitle: '4. ТЕПЕР ЗАЛИШИЛОСЯ ПЕРЕМОГТИ',
    tier: 'Рівень 4 · Аномалії',
    tierNum: 4,
    name: 'Dust 2',
    photoTitle: 'DUST 2 У БЕКРУМАХ',
    voiceover: 'Даст два у Бекрумах.',
    backupTitle: 'ЗНАЙОМА МАПА В ЧУЖОМУ СВІТІ',
  },

  /* Глава 5 (43–53) */
  {
    id: 43,
    numStr: '43',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Nextbots & Update 1.3.2 (324)',
    photoTitle: 'ТА САМА ГРА, ІНШИЙ ЖАНР',
    voiceover: 'Та сама гра, інший жанр.',
    backupTitle: 'ЕПОХА НЕКСТБОТІВ',
  },
  {
    id: 44,
    numStr: '44',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Кодові двері (код 4445)',
    photoTitle: 'КОД: 4445',
    voiceover: 'Код. Чотири. Чотири. Чотири. П’ять.',
    backupTitle: 'ЧОТИРИ ЦИФРИ ДО МАГАЗИНУ',
  },
  {
    id: 45,
    numStr: '45',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Shop',
    photoTitle: 'МАГАЗИН СЕРЕД ХАОСУ',
    voiceover: 'Магазин серед хаосу.',
    backupTitle: 'КУДИ ЙТИ ПО ЗБРОЮ',
  },
  {
    id: 46,
    numStr: '46',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Skibidi toilet',
    photoTitle: 'ЦЕ ПРОДАВЕЦЬ, НЕ ВОРОГ',
    voiceover: 'Це продавець, не ворог.',
    backupTitle: 'ЗБРОЯ ВІД СКІБІДІ',
  },
  {
    id: 47,
    numStr: '47',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Skibidi strider',
    photoTitle: 'ХТО ЗА СПИНОЮ ПРОДАВЦЯ?',
    voiceover: 'Хто за спиною продавця?',
    backupTitle: 'ПОДИВИСЯ НА ЗАДНІЙ ПЛАН',
  },
  {
    id: 48,
    numStr: '48',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Телевізори та Lays',
    photoTitle: 'ПЕРЕКУС У БЕКРУМАХ',
    voiceover: 'Перекус у бекрумах.',
    backupTitle: 'ЧИПСИ Й ТАБЛИЦІ ЛІДЕРІВ',
  },
  {
    id: 49,
    numStr: '49',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Тир',
    photoTitle: 'ПЕРЕПОЧИНОК У ТИРІ',
    voiceover: 'Перепочинок у тирі.',
    backupTitle: 'СТРІЛЬБА БЕЗ ПОГОНІ',
  },
  {
    id: 50,
    numStr: '50',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Секретна кімната',
    photoTitle: 'КІМНАТА З КОТИКОМ',
    voiceover: 'Кімната з котиком.',
    backupTitle: 'ЗООПАРК ДЛЯ НЕКСТБОТІВ',
  },
  {
    id: 51,
    numStr: '51',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Хінкалі',
    photoTitle: 'НАВІЩО ТУТ ХІНКАЛІ?',
    voiceover: 'Навіщо тут хінкалі?',
    backupTitle: 'КУЛІНАРІЯ МІЖ ПОГОНЯМИ',
  },
  {
    id: 52,
    numStr: '52',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Хвилі зомбі',
    photoTitle: 'ПЛАН НА ХВИЛІ ЗОМБІ',
    voiceover: 'План на хвилі зомбі.',
    backupTitle: 'НЕЗДІЙСНЕНИЙ РЕЖИМ',
  },
  {
    id: 53,
    numStr: '53',
    chapterId: 5,
    chapterTitle: '5. БУДЬ ЛАСКА, НЕ ПАНІКУЙТЕ',
    tier: 'Рівень 5 · Некстботи',
    tierNum: 5,
    name: 'Soul Goodman',
    photoTitle: 'ПОЧУВ МУЗИКУ — БІЖИ',
    voiceover: 'Почув музику — біжи.',
    backupTitle: 'ПЕРЕСЛІДУВАЧ, ЯКОГО НЕ СПИНИТИ',
  },

  /* Глава 6 (54–58) */
  {
    id: 54,
    numStr: '54',
    chapterId: 6,
    chapterTitle: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    tier: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    name: 'Backrooms FPS (146)',
    photoTitle: 'БАЗА',
    voiceover: 'База.',
    backupTitle: 'ВЕРСІЯ ПЛЕЙСА 146',
  },
  {
    id: 55,
    numStr: '55',
    chapterId: 6,
    chapterTitle: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    tier: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    name: 'ACS',
    photoTitle: 'ГОТОВА ОСНОВА ДЛЯ СТРІЛЬБИ',
    voiceover: 'Готова основа для стрільби.',
    backupTitle: 'З ЧОГО ПОЧАЛАСЯ СТРІЛЬБА',
  },
  {
    id: 56,
    numStr: '56',
    chapterId: 6,
    chapterTitle: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    tier: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    name: 'Old backrooms map',
    photoTitle: 'СТАРИЙ ЖОВТИЙ ЛАБІРИНТ',
    voiceover: 'Старий жовтий лабіринт.',
    backupTitle: 'ТИША РАННЬОЇ МАПИ',
  },
  {
    id: 57,
    numStr: '57',
    chapterId: 6,
    chapterTitle: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    tier: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    name: 'Fire exit',
    photoTitle: 'ВИХІД У ПОРОЖНЕЧУ',
    voiceover: 'Вихід у порожнечу.',
    backupTitle: 'ДВЕРІ ЗА МЕЖУ МАПИ',
  },
  {
    id: 58,
    numStr: '58',
    chapterId: 6,
    chapterTitle: '6. ТЕПЕР МОЖНА БЕЗ ПЛАНУ',
    tier: 'Рівень 6 · Точка нуль',
    tierNum: 6,
    name: 'Backrooms Test Place (34)',
    photoTitle: 'ТОЧКА НУЛЬ: 34',
    voiceover: 'Точка нуль. Тридцять чотири.',
    backupTitle: 'КОРОБКА, З ЯКОЇ ПОЧИНАЛИ',
  },
];
